[project]
name = "fintech"
version = "0.1.0"
description = "HeyMax AI Itinerary Planner Data Extraction Pipeline"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apify>=3.0.2",
    "dotenv>=0.9.9",
    "youtube-transcript-api>=1.2.3",
]
